
# Build matrix
language: node_js
matrix:
  include:

    # Run linter
    - node_js: '6'

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# Build script
script:
  - 'make verify'
